services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=valobuddy
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - ./database/postgres-data:/var/lib/postgresql/data
