services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=valobuddy
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - ./database/postgres-data:/var/lib/postgresql/data
  app:
    depends_on:
      postgres:
        condition: service_started
    build: .
    environment:
      - APP_NAME=ValoBuddy
      - APP_ENV=production
      - APP_KEY=base64:N/qFkC//5QoKGN84xNooH+0M+Nw896U4pJlCo7BXgQU=
      - APP_TIMEZONE=UTC
      - APP_LOCALE=en
      - APP_MAINTENANCE_DRIVER=file
      - BCRYPT_ROUNDS=12
      - LOG_CHANNEL=stderr
      - LOG_LEVEL=info
      - LOG_STDERR_FORMATTER=Monolog\Formatter\JsonFormatter
      - DB_CONNECTION=pgsql
      # This is usually set to 127.0.0.1, but since we're running with Docker
      # Compose, we can point to a service name as a host name/domain name.
      # Pretty cool.
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=valobuddy
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - SESSION_DRIVER=database
      - SESSION_LIFETIME=120
      - SESSION_ENCRYPT=false
      - SESSION_PATH=/
      - SESSION_DOMAIN=null
      - SESSION_SECURE_COOKIE=true
    ports:
      - "80:8080"
